export const COLL_DEPTH_DATA_BUY = 'COLL_DEPTH_DATA_BUY'

export const COLL_DEPTH_DATA_SELL = 'COLL_DEPTH_DATA_SELL'

export const COLL_TICKER_HISTORY = 'COLL_TICKER_HISTORY'

export const COLL_PAIRS = 'COLL_PAIRS'

export const COLL_TRADE_HISTORY = 'COLL_TRADE_HISTORY'

export const COLL_CURRENT_PRICE = 'COLL_CURRENT_PRICE'

export const COLL_CURRENT_TICKER_24 = 'COLL_CURRENT_TICKER_24'
