export const SELECT_PAIR = 'SELECT_PAIR'

export const SET_PRICE_HISTORY_INTERVAL = 'SET_PRICE_HISTORY_INTERVAL'

export const SET_BALANCES = 'SET_BALANCES'

export const PLACE_ORDER = 'PLACE_ORDER'

export const SET_ORDERS = 'SET_ORDERS'

export const ADD_ORDER = 'ADD_ORDER'

export const UPD_ORDER = 'UPD_ORDER'

export const SET_PAIRS = 'SET_PAIRS'

export const UPD_PAIRS = 'UPD_PAIRS'

export const SET_WALLET_INFO = 'SET_WALLET_INFO'

export const SET_ORDERS_HISTORY = 'SET_ORDERS_HISTORY'

export const SET_LOADING = 'SET_LOADING'

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'

export const SET_CHANGE_PASSWORD_RESULT = 'SET_CHANGE_PASSWORD_RESULT'

export const UPD_USER = 'UPD_USER'

export const SET_USER = 'SET_USER'

export const UPD_F2A_SECRET = 'UPD_F2A_SECRET'

export const SET_F2A_SECRET = 'SET_F2A_SECRET'

export const SEND_F2A_OTP = 'SEND_F2A_OTP'

export const SET_SEND_F2A_OTP_RESULT = 'SET_SEND_F2A_OTP_RESULT'

export const EDIT_ORDER = 'EDIT_ORDER'

export const DEL_ORDER = 'DEL_ORDER'

export const OPEN_ORDER = 'OPEN_ORDER'

export const SET_PAIR_FAV = 'SET_PAIR_FAV'

export const REVERT_PAIR_FAV = 'REVERT_PAIR_FAV'

export const SOCKET_UP = 'SOCKET_UP'

export const SOCKET_UPPED = 'SOCKET_UPPED'

export const SOCKET_CONNECT = 'SOCKET_CONNECT'

export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT'

export const LOGOUT_USER = 'LOGOUT_USER'

export const EXPORT_ARRAY_AS_CSV = 'EXPORT_ARRAY_AS_CSV'

export const COPY_TO_CLIPBOARD = 'COPY_TO_CLIPBOARD'

export const COPY_REFLINK = 'COPY_REFLINK'

export const TOKEN_EXPIRED = 'TOKEN_EXPIRED'

export const SET_REF_COUNT = 'SET_REF_COUNT'

export const SET_REF_GAIN = 'SET_REF_GAIN'

export const SET_BEM_GAIN = 'SET_BEM_GAIN'

export const SET_DEPOSITS_HISTORY = 'SET_DEPOSITS_HISTORY'

export const UPLOAD_VERIFICATION_DOCS = 'UPLOAD_VERIFICATION_DOCS'

export const WITHDRAW = 'WITHDRAW'

export const SET_WITHDRAW_PROCESSING = 'SET_WITHDRAW_PROCESSING'
